### PR TITLE
add json_api_org endpoints for haikus and basic controller methods

### PR DESCRIPTION
**Pull request by justin-rhoades**
Created endpoints for haikus with basic request specs and controller.

### CODE REVIEW

**Comment by thomas-jung** [comment]
Simplecov is showing 70/74 lines covered for testing. 3 of those lines are untested lines from your haikus controller. You can see the report from spec/simplecov/index.html. It would also be good to add some seed data so we can try out the endpoints with curl or postman. Also, for your haiku#update test on line 48, would that test be accurate?

**Comment by justin-rhoades** [comment]
Simplecov should be 100%, and I updated the tests to accurately reflect creating and patching methods. To do so, I wanted to create an appropriately editable attribute, so I created a migration that added a title string to the haiku model (seemed the most plausible addition). Also added seeds for 10 haikus with titles.

**Comment by kangkyu** [comment]
By the way, why do we have **31** commits in one pull request? :open_mouth:

**Comment by thomas-jung** [comment]
This looks good to me :+1:

**Comment by kangkyu** [comment]
:+1:

**Comment by tphyahoo** [comment]
kangkyu: I only see one commit.  did the 31 commits get squished into one?

btw I just joined haikus and have been lurking a few days, till now. hi everyone.

**Comment by kangkyu** [comment]
@tphyahoo I'm not sure but it happens when you simply `pull` from different tip, not `rebase`. Was it like that @justin-rhoades ? By the way it seems this branch can be deleted. :cake:

**Pull request merged**
