### PR TITLE
Ran rspec install to get missing spec/rails_helper.rb file.

### PR DESCRIPTION
**Pull request by rlcheng**
When I initially setup rspec I think I ran init and it only generated spec/spec_helper.rb. Was missing spc/rails_helper.rb.

### CODE REVIEW

**Comment by thomas-jung** [comment]
looks good to me :thumbsup:

**Comment by kangkyu** [comment]
:+1: please merge

**Comment by kangkyu** [comment]
By the way, it looks like we don't need something like

``` rb
# config/application.rb
config.generators do |g|
  g.test_framework :rspec
end
```

But why? I guess it's done by `gem 'rspec-rails'` automatically.

**Comment by rlcheng** [comment]
Where is that line from?

**Comment by kangkyu** [comment]
http://guides.rubyonrails.org/configuring.html#configuring-generators

**Pull request merged**
