### PR TITLE
Add users endpoints/103749622-pan

### PR DESCRIPTION
**Pull request by ypan887**
Hi, this is my first pull request, if I didn't do it right please let me know. 
I add endpoints create, index, show, update, and destroy using  jsonapi serializers and spec test.
I add   gem 'responders', '~> 2.0', and gem 'jsonapi-serializers'. 
I also add email validation to user and test it.

### CODE REVIEW

**Comment by kangkyu** [comment]
Don't we better have it in different way, without `responders` and `jsonapi-serializers`? For we already have `active_model_serializers` on our `Gemfile`.

**Comment by thomas-jung** [comment]
Kangkyu is right about that. Also you would want to double check your text editor settings for your tabs. We follow https://github.com/styleguide/ruby which has 2 spaces = 1 tab so everyone's formatting is the same.

**Comment by ypan887** [comment]
em, yes, I didn't realize that I can use active_model_serializers. I will
change that. Thank you.

Kang-Kyu Lee notifications@github.com于2015年10月6日周二 上午9:38写道：

**Comment by ypan887** [comment]
Thank you. I just read the guideline and I will check my code and fix
styling.

Thomas Jung notifications@github.com于2015年10月6日周二 上午9:57写道：

**Comment by ypan887** [comment]
Hi, so I change back to use active_model_serializers and fixed indentation. I just push back to my branch, I hope it will update me pull request.

**Comment by ypan887** [comment]
Hi, so I change back to use active_model_serializers and fixed indentation. I just push back to my branch, I hope it will update me pull request.

**Pull request closed without merging**
