### PR TITLE
add user endpoint, request test, and fixed indentation

### PR DESCRIPTION
**Pull request by ypan887**
HI thomas, I fixed tab in those two files, fixed router, and I am pushing my branch to origin, so I am submitting a new PR. Thank you.

### CODE REVIEW

**Comment by ypan887** [comment]
I am not sure about the check failure above. It seems to be building an automatic test environment for my code, but it complains about ruby version. I see it is using rvm, but I am using rbenv on my local machine. If I run ruby -v, I get ruby 2.2.2p95, so why are the test using ruby 1.9.3 and can't find my current ruby version. Is it looking for ruby on my machine or on some remote server?

**Comment by thomas-jung** [comment]
It looks like there was a problem with Travis CI. Richard took care of it and merged the changes into master. If you rebase your feature branch with master and push it back up, it should pass.

**Comment by ypan887** [comment]
OK, I updated my PR. Now all three check is green.

**Comment by thomas-jung** [comment]
:+1: This looks really good. Just need 1 more person to approve, then you can merge.

**Comment by rlcheng** [comment]
:+1:  merge time!

**Pull request merged**
