### PR TITLE
Add users controller

### PR DESCRIPTION
**Pull request by kkchu791**

### CODE REVIEW

**Comment by thomas-jung** [comment]
You're on the right track, but what about create, show, and update?

**Comment by kkchu791** [comment]
Updated with rest of methods.

**Comment by thomas-jung** [comment]
Simplecov showing 2 lines missed in your users controller. Also, you wouldn't need users#new and users#edit routes.

**Comment by thomas-jung** [comment]
Sorry Kirk, this ticket is completed and merged already. I'm going to close this one but there are more tickets in the backlog :smile:

**Pull request closed without merging**
